In [13]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import math

In [ ]:
df = pd.DataFrame(pd.read_csv("C:/Users/divya/AIML/Cr-02-ML_AZ/MLAZ_Course/datasets/Ads_CTR_Optimisation.csv"))

df.head()

   Ad 1  Ad 2  Ad 3  Ad 4  Ad 5  Ad 6  Ad 7  Ad 8  Ad 9  Ad 10
0     1     0     0     0     1     0     0     0     1      0
1     0     0     0     0     0     0     0     0     1      0
2     0     0     0     0     0     0     0     0     0      0
3     0     1     0     0     0     0     0     1     0      0
4     0     0     0     0     0     0     0     0     0      0

In [6]:
dataset = pd.read_csv("C:/Users/divya/AIML/Cr-02-ML_AZ/MLAZ_Course/datasets/Ads_CTR_Optimisation.csv")
dataset.head()

   Ad 1  Ad 2  Ad 3  Ad 4  Ad 5  Ad 6  Ad 7  Ad 8  Ad 9  Ad 10
0     1     0     0     0     1     0     0     0     1      0
1     0     0     0     0     0     0     0     0     1      0
2     0     0     0     0     0     0     0     0     0      0
3     0     1     0     0     0     0     0     1     0      0
4     0     0     0     0     0     0     0     0     0      0

In [11]:
N = len(dataset)
d = len(dataset.columns)
ads_selected = []
numbers_of_selections = [0] * d
sum_of_rewards = [0] * d
total_rewards = 0

In [ ]:
for n in range(0, N):
    ad = 0
    max_upper_bound = 0
    for i in range(0, d):
        if(numbers_of_selections[i] > 0):
            average_reward = sum_of_rewards[i]/numbers_of_selections[i]
            delta_i = math.sqrt(3/2 * math.log(n+ 1)/numbers_of_selections[i])
            upper_bound = average_reward + delta_i
        else:
            upper_bound = 1e400 # a very large number
        if(upper_bound > max_upper_bound):
            max_upper_bound = upper_bound
            ad = i
    ads_selected.append(ad)
    numbers_of_selections[ad] = numbers_of_selections[ad] + 1
    rewards = dataset.values[n, ad]
    sum_of_rewards[ad] = sum_of_rewards[ad] + rewards
    total_rewards = total_rewards + rewards